# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/olile/Dokumenty/pwr/lista4L3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/olile/Dokumenty/pwr/lista4L3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/olile/Dokumenty/pwr/lista4L3/CMakeFiles /home/olile/Dokumenty/pwr/lista4L3//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/olile/Dokumenty/pwr/lista4L3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lista4L3

# Build rule for target.
lista4L3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lista4L3
.PHONY : lista4L3

# fast build rule for target.
lista4L3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/build
.PHONY : lista4L3/fast

1cpp/Circle.o: 1cpp/Circle.cpp.o
.PHONY : 1cpp/Circle.o

# target to build an object file
1cpp/Circle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Circle.cpp.o
.PHONY : 1cpp/Circle.cpp.o

1cpp/Circle.i: 1cpp/Circle.cpp.i
.PHONY : 1cpp/Circle.i

# target to preprocess a source file
1cpp/Circle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Circle.cpp.i
.PHONY : 1cpp/Circle.cpp.i

1cpp/Circle.s: 1cpp/Circle.cpp.s
.PHONY : 1cpp/Circle.s

# target to generate assembly for a file
1cpp/Circle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Circle.cpp.s
.PHONY : 1cpp/Circle.cpp.s

1cpp/Diamond.o: 1cpp/Diamond.cpp.o
.PHONY : 1cpp/Diamond.o

# target to build an object file
1cpp/Diamond.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Diamond.cpp.o
.PHONY : 1cpp/Diamond.cpp.o

1cpp/Diamond.i: 1cpp/Diamond.cpp.i
.PHONY : 1cpp/Diamond.i

# target to preprocess a source file
1cpp/Diamond.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Diamond.cpp.i
.PHONY : 1cpp/Diamond.cpp.i

1cpp/Diamond.s: 1cpp/Diamond.cpp.s
.PHONY : 1cpp/Diamond.s

# target to generate assembly for a file
1cpp/Diamond.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Diamond.cpp.s
.PHONY : 1cpp/Diamond.cpp.s

1cpp/Hexagon.o: 1cpp/Hexagon.cpp.o
.PHONY : 1cpp/Hexagon.o

# target to build an object file
1cpp/Hexagon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Hexagon.cpp.o
.PHONY : 1cpp/Hexagon.cpp.o

1cpp/Hexagon.i: 1cpp/Hexagon.cpp.i
.PHONY : 1cpp/Hexagon.i

# target to preprocess a source file
1cpp/Hexagon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Hexagon.cpp.i
.PHONY : 1cpp/Hexagon.cpp.i

1cpp/Hexagon.s: 1cpp/Hexagon.cpp.s
.PHONY : 1cpp/Hexagon.s

# target to generate assembly for a file
1cpp/Hexagon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Hexagon.cpp.s
.PHONY : 1cpp/Hexagon.cpp.s

1cpp/Parallelogram.o: 1cpp/Parallelogram.cpp.o
.PHONY : 1cpp/Parallelogram.o

# target to build an object file
1cpp/Parallelogram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Parallelogram.cpp.o
.PHONY : 1cpp/Parallelogram.cpp.o

1cpp/Parallelogram.i: 1cpp/Parallelogram.cpp.i
.PHONY : 1cpp/Parallelogram.i

# target to preprocess a source file
1cpp/Parallelogram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Parallelogram.cpp.i
.PHONY : 1cpp/Parallelogram.cpp.i

1cpp/Parallelogram.s: 1cpp/Parallelogram.cpp.s
.PHONY : 1cpp/Parallelogram.s

# target to generate assembly for a file
1cpp/Parallelogram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Parallelogram.cpp.s
.PHONY : 1cpp/Parallelogram.cpp.s

1cpp/Pentagon.o: 1cpp/Pentagon.cpp.o
.PHONY : 1cpp/Pentagon.o

# target to build an object file
1cpp/Pentagon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Pentagon.cpp.o
.PHONY : 1cpp/Pentagon.cpp.o

1cpp/Pentagon.i: 1cpp/Pentagon.cpp.i
.PHONY : 1cpp/Pentagon.i

# target to preprocess a source file
1cpp/Pentagon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Pentagon.cpp.i
.PHONY : 1cpp/Pentagon.cpp.i

1cpp/Pentagon.s: 1cpp/Pentagon.cpp.s
.PHONY : 1cpp/Pentagon.s

# target to generate assembly for a file
1cpp/Pentagon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Pentagon.cpp.s
.PHONY : 1cpp/Pentagon.cpp.s

1cpp/Quadrangle.o: 1cpp/Quadrangle.cpp.o
.PHONY : 1cpp/Quadrangle.o

# target to build an object file
1cpp/Quadrangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Quadrangle.cpp.o
.PHONY : 1cpp/Quadrangle.cpp.o

1cpp/Quadrangle.i: 1cpp/Quadrangle.cpp.i
.PHONY : 1cpp/Quadrangle.i

# target to preprocess a source file
1cpp/Quadrangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Quadrangle.cpp.i
.PHONY : 1cpp/Quadrangle.cpp.i

1cpp/Quadrangle.s: 1cpp/Quadrangle.cpp.s
.PHONY : 1cpp/Quadrangle.s

# target to generate assembly for a file
1cpp/Quadrangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Quadrangle.cpp.s
.PHONY : 1cpp/Quadrangle.cpp.s

1cpp/Rectangle.o: 1cpp/Rectangle.cpp.o
.PHONY : 1cpp/Rectangle.o

# target to build an object file
1cpp/Rectangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Rectangle.cpp.o
.PHONY : 1cpp/Rectangle.cpp.o

1cpp/Rectangle.i: 1cpp/Rectangle.cpp.i
.PHONY : 1cpp/Rectangle.i

# target to preprocess a source file
1cpp/Rectangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Rectangle.cpp.i
.PHONY : 1cpp/Rectangle.cpp.i

1cpp/Rectangle.s: 1cpp/Rectangle.cpp.s
.PHONY : 1cpp/Rectangle.s

# target to generate assembly for a file
1cpp/Rectangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Rectangle.cpp.s
.PHONY : 1cpp/Rectangle.cpp.s

1cpp/Shape.o: 1cpp/Shape.cpp.o
.PHONY : 1cpp/Shape.o

# target to build an object file
1cpp/Shape.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Shape.cpp.o
.PHONY : 1cpp/Shape.cpp.o

1cpp/Shape.i: 1cpp/Shape.cpp.i
.PHONY : 1cpp/Shape.i

# target to preprocess a source file
1cpp/Shape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Shape.cpp.i
.PHONY : 1cpp/Shape.cpp.i

1cpp/Shape.s: 1cpp/Shape.cpp.s
.PHONY : 1cpp/Shape.s

# target to generate assembly for a file
1cpp/Shape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Shape.cpp.s
.PHONY : 1cpp/Shape.cpp.s

1cpp/Square.o: 1cpp/Square.cpp.o
.PHONY : 1cpp/Square.o

# target to build an object file
1cpp/Square.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Square.cpp.o
.PHONY : 1cpp/Square.cpp.o

1cpp/Square.i: 1cpp/Square.cpp.i
.PHONY : 1cpp/Square.i

# target to preprocess a source file
1cpp/Square.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Square.cpp.i
.PHONY : 1cpp/Square.cpp.i

1cpp/Square.s: 1cpp/Square.cpp.s
.PHONY : 1cpp/Square.s

# target to generate assembly for a file
1cpp/Square.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/Square.cpp.s
.PHONY : 1cpp/Square.cpp.s

1cpp/main.o: 1cpp/main.cpp.o
.PHONY : 1cpp/main.o

# target to build an object file
1cpp/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/main.cpp.o
.PHONY : 1cpp/main.cpp.o

1cpp/main.i: 1cpp/main.cpp.i
.PHONY : 1cpp/main.i

# target to preprocess a source file
1cpp/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/main.cpp.i
.PHONY : 1cpp/main.cpp.i

1cpp/main.s: 1cpp/main.cpp.s
.PHONY : 1cpp/main.s

# target to generate assembly for a file
1cpp/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lista4L3.dir/build.make CMakeFiles/lista4L3.dir/1cpp/main.cpp.s
.PHONY : 1cpp/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lista4L3"
	@echo "... 1cpp/Circle.o"
	@echo "... 1cpp/Circle.i"
	@echo "... 1cpp/Circle.s"
	@echo "... 1cpp/Diamond.o"
	@echo "... 1cpp/Diamond.i"
	@echo "... 1cpp/Diamond.s"
	@echo "... 1cpp/Hexagon.o"
	@echo "... 1cpp/Hexagon.i"
	@echo "... 1cpp/Hexagon.s"
	@echo "... 1cpp/Parallelogram.o"
	@echo "... 1cpp/Parallelogram.i"
	@echo "... 1cpp/Parallelogram.s"
	@echo "... 1cpp/Pentagon.o"
	@echo "... 1cpp/Pentagon.i"
	@echo "... 1cpp/Pentagon.s"
	@echo "... 1cpp/Quadrangle.o"
	@echo "... 1cpp/Quadrangle.i"
	@echo "... 1cpp/Quadrangle.s"
	@echo "... 1cpp/Rectangle.o"
	@echo "... 1cpp/Rectangle.i"
	@echo "... 1cpp/Rectangle.s"
	@echo "... 1cpp/Shape.o"
	@echo "... 1cpp/Shape.i"
	@echo "... 1cpp/Shape.s"
	@echo "... 1cpp/Square.o"
	@echo "... 1cpp/Square.i"
	@echo "... 1cpp/Square.s"
	@echo "... 1cpp/main.o"
	@echo "... 1cpp/main.i"
	@echo "... 1cpp/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

